### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by Creator** [Exerro/Sheets#1]
:question:

**Comment by exerro** [comment]
A new UI framework.

**Comment by Creator** [comment]
wasn't Flare a GUI framework too?

**Comment by exerro** [comment]
Yup, but this one is newer and better.

```
<theme name=Theme1>
    <button>
        <colour default=orange pressed=red/>
        <textColour default=white pressed=black/>
    </button>
</theme>
```

**Comment by Creator** [comment]
More like HTML?

**Comment by exerro** [comment]
XML, but yeah. You'll be able to load entire applications from this format theoretically. Anyway, jump on the [Gitter Chat](https://gitter.im/Exerro/Sheets) if you want to talk more.
