### ISSUE TITLE
Button held and when slid off button and released, stays pressed colour.

### ISSUE THREAD

**Issue by ghost** [Exerro/Sheets#10]
I declared a Button in my code, and when I held my left-button on the button and slid it across while still holding it down, but it stayed the same colour as it does when clicked.

A easy fix for this is to click anywhere on the application, but still a bug as stated.

**Comment by demhydraz** [comment]
Pretty sure this isn't a bug as much as it is a technical limitation. From my non-educated perspective of things, the colour is reset when a mouse_up event is fired, and in your case, it doesn't fire.

**Comment by exerro** [comment]
Can you elaborate what you mean exactly? Are you saying you pressed the mouse button, moved the mouse off the button, then released it, and it stayed as if it were pressed?

**Comment by ghost** [comment]
Yes Exerro, what you said.

**Comment by exerro** [comment]
I can't seem to replicate that. It resets its colour just fine when I release the mouse button. Can you send your code (preferably make it as small as you can, i.e. just the button definition)?

**Comment by ghost** [comment]
Of course.

``` lua
local loginSubmit = screen + sheets.Button( 3, 10, 21, 3, "Login" )
```

**Comment by exerro** [comment]
From the following code:

``` lua
local sheets = dofile "sheets_builds/lib.lua"

local application = sheets.Application()
local screen = application.screen

local loginSubmit = screen + sheets.Button( 3, 10, 21, 3, "Login" )

application:run()
```

I got this:

![](http://puu.sh/lyHbx/6449ba55a8.gif)

**Comment by exerro** [comment]
Sorry, that wasn't very descriptive. I can't replicate the issue you're describing, as that shows. I pressed inside the button, moved off the button, then released it, and as you can see the colour changed just fine.

**Comment by ghost** [comment]
Weird, I am not sure at all why that is happening. I will give an update tomorrow.

EDIT: Just realised, it starts to do it every 2/5 times you do it, so it isn't each time.

**Comment by exerro** [comment]
It might help to put the full code on something like [pastebin](http://pastebin.com/). I'll give it a test, and if it works fine for me, it's probably either an emulator problem or something wrong with your Sheets build.

**Comment by exerro** [comment]
Closed as the issue was never replicated and lots of internals are being rewritten.
