### ISSUE TITLE
Complete Documentation

### ISSUE THREAD

**Issue by viluon** [Exerro/Sheets#2]
There's still a plenty of work left over at the [Sheets wiki](https://github.com/Exerro/Sheets/wiki). 

**Note**: This issue isn't meant to make the docs perfect, but instead keep track of what is _not documented at all_. For improving the quality of the wiki with examples, refer to #4.
- [ ] Create Getting Started with Dynamic Values (tutorial)
- [ ] Complete Sheets basics tutorials
- [ ] Create Building Sheets [tutorial series](https://github.com/Exerro/Sheets/wiki/Tutorials#building-sheets)
- [ ] Create Sheets advanced topics [tutorial series](https://github.com/Exerro/Sheets/wiki/Tutorials#sheets-advanced-topics)
- [ ] Create Sheets internals [tutorial series](https://github.com/Exerro/Sheets/wiki/Tutorials#sheets-internals)
- [ ] Port [shader](https://github.com/Exerro/CC-Graphics-Library/blob/master/docs/shader.md) and [colour](https://github.com/Exerro/CC-Graphics-Library/blob/master/docs/colour.md) docs over to the wiki

Already done:
- [x] Document `Application:addThread()`
- [x] Move the old docs to the wiki #3

**Comment by hbomb79** [comment]
Better get to it then!!!!! I AM WAITING.

**Comment by exerro** [comment]
[Application:addThread()](https://github.com/Exerro/Sheets/wiki/Application#addthread) is documented.

**Comment by exerro** [comment]
Closed due to large internal rewrite - documentation features to be completed will be submitted in future issues.
