### ISSUE TITLE
Add examples to all wiki pages

### ISSUE THREAD

**Issue by viluon** [Exerro/Sheets#4]
We should have commented code examples for every element, class, library and tutorial out there.
- [ ] [Draggable](https://github.com/Exerro/Sheets/wiki/Draggable)
- [ ] [Image](https://github.com/Exerro/Sheets/wiki/Image)
- [ ] [Panel](https://github.com/Exerro/Sheets/wiki/Panel)
- [ ] [ScrollContainer](https://github.com/Exerro/Sheets/wiki/ScrollContainer)
- [ ] [Text](https://github.com/Exerro/Sheets/wiki/Text)
- [ ] [TextInput](https://github.com/Exerro/Sheets/wiki/TextInput)

These pages already have examples:
- [X] [timer](https://github.com/Exerro/Sheets/wiki/timer)

Feel free to add ~~any pages that need examples~~ all pages to this list.

**Comment by exerro** [comment]
See #8.
