### ISSUE TITLE
Normalise easing functions

### ISSUE THREAD

**Issue by SquidDev** [Exerro/Sheets#44]
Easing functions should just take a time value between 0 and 1, and return a value between 0 and 1. Most easing functions will be defined of the form `u + d * f(t)` so this shouldn't be a problem anyway.

However, I note that `exit` [does not obey](https://github.com/Exerro/Sheets/blob/develop/enum/Easing.lua#L16-L18) this formula, and so you'd probably have to tweak the start and end values instead.

**Comment by exerro** [comment]
Sounds good. In the `develop` branch, animations (transitions) are handled slightly differently, so the redundant line you referenced is no longer present.

Not sure how `easing_entrance` doesn't obey that formula, but yes, `easing_exit` works [a little differently](https://github.com/Exerro/Sheets/blob/develop/enum/Easing.lua#L17). However, with a little factorisation and re-arrangement, the expression
```lua
-d * cos(t * halfpi) + d + u
```
can become
```lua
u + d * (1 - cos(t * halfpi))
```
which satisfies the form `u + d * f(t)` (where `f(t) = cos(t * halfpi)`)

**Comment by SquidDev** [comment]
🎉 👍
