### ISSUE TITLE
Remove builds from master branch and start using GitHub releases

### ISSUE THREAD

**Issue by viluon** [Exerro/Sheets#5]
Let's switch to a cleaner, nicer and more polished way of releasing. If we start using GitHub releases @Exerro, users will no longer need to download the whole repo and dig through the directory structure to find the final executable. Releases will also separate the source code from actual builds, resulting in less mess and no need to recompile Sheets for every commit.
- [x] Adopt GitHub releases

**Comment by exerro** [comment]
Yeah that sounds good. I wasn't really aware of GitHub releases, otherwise I would've used it. Would you mind managing the releases @viluon?

**Comment by viluon** [comment]
When I learn how to actually build Sheets and create the tutorial @Exerro :D
