### ISSUE TITLE
Fix Sheet calling non-existent method :implements()

### ISSUE THREAD

**Issue by viluon** [Exerro/Sheets#6]
The following code compiled will result in error `core.Sheet:122: Attempt to call method 'implements' (a nil value)` when clicked on the myDraggable object on screen.

``` Lua

-- @define SHEETS_CORE_ELEMENTS
-- @define SHEETS_MINIFY false
-- @include sheets

local application = Application()
local screen = application.screen

local myDraggable = screen + Draggable( 2, 2, 12, 1, "Hello World!" )

function myDraggable:onDrop()
    application:stop()
end

application:run()

```

![](https://i.gyazo.com/886c71607fa429fdf0a865b8fbe0aff4.png)

Lines 121 - 122 of src/core/Sheet.lua look like this

``` Lua
    -- fix this
    if parent and ( not class.isInstance( parent ) or not parent:implements( IChildContainer ) ) then return error( "expected IChildContainer parent, got " .. class.type( parent ) ) end
```

**Comment by exerro** [comment]
Ah yeah, this was when Class:implements() returned a bool of whether the class implemented that interface. I'll fix it now.
